### ISSUE TITLE
TypeError: Cannot read property 'prefix' of null

### ISSUE THREAD

**Issue by InfaceMan** [rsuite/rsuite-table#21]
我在服务端引用 
import {Table, Column, Cell} from 'rsuite-table';
webpack 打包编译 报 ‘Variable @H500 is undefined’ 这个错误。我在index.less 声明了 这个变量 @H500: blue 后 再打包编译  TypeError: Cannot read property 'prefix' of null。
详细错误如下：
D:\React 渲染\MyReact-table\node_modules\dom-lib\lib\transition\index.js:59
    prefix = _getTransitionPropert.prefix,
                                   ^
TypeError: Cannot read property 'prefix' of null
    at Object.<anonymous> (D:\React 渲染\MyReact-table\node_modules\dom-lib\lib\transition\index.js:59:36)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\React 渲染\MyReact-table\node_modules\dom-lib\lib\index.js:60:20)
    at Module._compile (module.js:641:30)

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite-table/issues/19

**Comment by InfaceMan** [comment]
安装了 rsuite-theme 后，编译报错 
 ERROR in ./public/css/style.less
Module build failed: ModuleBuildError: Module build failed:

// It is hacky way to make this function will be compiled preferentially by less
.colorPaletteMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in D:\React 渲染\MyReact-table\node_modules\rsuite-theme\dist\less\mixins\palette.less (line 46, column 0)
    at runLoaders (D:\React 渲染\MyReact-table\node_modules\webpack\lib\NormalModule.js:252:20)
    at D:\React 渲染\MyReact-table\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\React 渲染\MyReact-table\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (D:\React 渲染\MyReact-table\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./public/css/style.less
rsuite-table插件可以在服务端渲染吗？(将 `<Table>`组件 装换成 对应的html代码)。
我在路由文件中这样写
   ` let _roothtml= renderToString( (
          <Table data = {dataList} >
              <Column  width = {100} sort fixed resizable>
                  <HeaderCell>ID</HeaderCell>
                  <Cell dataKey="id"></Cell>
              </Column>
              <Column  width = {100} sort resizable>
                  <HeaderCell>Name</HeaderCell>
                  <Cell dataKey="name"></Cell>
              </Column>
              <Column  width = {100} sort resizable>
                  <HeaderCell>Email</HeaderCell>
                  <Cell dataKey="email"></Cell>
              </Column>
              <Column  width = {100} resizable>
                  <HeaderCell>Avartar</HeaderCell>
                  <ImageCell dataKey="avartar"></ImageCell>
              </Column>
          </Table>
        )）  `
 _roothtml 变量能得到对应的html吗？

**Comment by simonguo** [comment]
@InfaceMan  目前不支持服务端渲染

**Comment by simonguo** [comment]
@InfaceMan 当前最新版本已经支持服务端渲染，另外，你上面的报错，需要在 lessLoader 配置 `javascriptEnabled: true`
